seu_nome = str(input("digite nome:"))
num_tel = str(input("digite seu telefone:"))
email = str(input("digite seu email:"))
endereço = str(input("digite seu endereço:"))
sexo = str(input("digite seu sexo:"))
salario = str(input("digite seu salario:"))
idade = (input("digite sua idade:"))

print("nome: ,seu_nome")
print("numero de telefone:",num_tel)
print("e-mail:", email)
print("endereço:", endereço)
print("sexo", sexo)
print("salario:", salario)
print("idade:", idade)